# Generated by Django 4.2.2 on 2023-06-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("dob", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Punjab", "Punjab"),
                            ("Sindh", "Sindh"),
                            ("KPK", "KPK"),
                            ("Karachi", "Karachi"),
                        ],
                        max_length=100,
                    ),
                ),
                ("gender", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("pimage", models.ImageField(blank=True, upload_to="pimage")),
                ("rdoc", models.FileField(blank=True, upload_to="rdoc")),
                ("phone", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("skills", models.TextField()),
                ("experience", models.TextField()),
                ("education", models.TextField()),
                ("projects", models.TextField()),
                ("achievements", models.TextField()),
                ("hobbies", models.TextField()),
                ("languages", models.TextField()),
                ("interests", models.TextField()),
                ("references", models.TextField()),
            ],
        ),
    ]
