# Generated by Django 4.2.2 on 2023-06-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="interests",),
        migrations.RemoveField(model_name="profile", name="languages",),
        migrations.RemoveField(model_name="profile", name="references",),
        migrations.AlterField(
            model_name="profile",
            name="achievements",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="education",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="experience",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="hobbies",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="projects",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile", name="skills", field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="summary",
            field=models.TextField(max_length=1000),
        ),
    ]
